// THIS FILE IS AUTOGENERATED! DO NOT TRY TO EDIT!
// @ts-ignore
import { Context } from '@openland/context';
// @ts-ignore
import { Subspace } from '@openland/foundationdb';
// @ts-ignore
import { EntityStore } from '@openland/foundationdb-entity';
// @ts-ignore
import { AtomicIntegerFactory, AtomicBooleanFactory } from '@openland/foundationdb-entity';

export class SimpleAtomicBooleanFactory extends AtomicBooleanFactory {

    static async create(store: EntityStore) {
        let directory = await store.resolveAtomicDirectory('simpleAtomicBoolean');
        return new SimpleAtomicBooleanFactory(store, directory);
    }

    private constructor(store: EntityStore, subspace: Subspace) {
        super(store, subspace);
    }

    byId(key: string) {
        return this._findById([key]);
    }
}

export class SimpleAtomicIntegerFactory extends AtomicIntegerFactory {

    static async create(store: EntityStore) {
        let directory = await store.resolveAtomicDirectory('simpleAtomicInteger');
        return new SimpleAtomicIntegerFactory(store, directory);
    }

    private constructor(store: EntityStore, subspace: Subspace) {
        super(store, subspace);
    }

    byId(key: string) {
        return this._findById([key]);
    }
}
