// THIS FILE IS AUTOGENERATED! DO NOT TRY TO EDIT!
// @ts-ignore
import * as t from 'io-ts';
// @ts-ignore
import { Context } from '@openland/context';
// @ts-ignore
import { Subspace } from '@openland/foundationdb';
// @ts-ignore
import { EntityStorage, BaseStore } from '@openland/foundationdb-entity';
// @ts-ignore
import { Entity, EntityFactory, EntityDescriptor, SecondaryIndexDescriptor } from '@openland/foundationdb-entity';

export interface SimpleEntityShape {
    id: string;
    value: string;
    value2: number;
    value3?: boolean | null | undefined;
}

export class SimpleEntity extends Entity<SimpleEntityShape> {
    get id(): string { return this._rawValue.id; }
    get value(): string {  return this._rawValue.value; }
    get value2(): number {  return this._rawValue.value2; }
    get value3(): boolean | null {  if (this._rawValue.value3 !== undefined && this._rawValue.value3 !== null) { return this._rawValue.value3; } else { return null; } }
}

export class SimpleEntityFactory extends EntityFactory<SimpleEntityShape, SimpleEntity> {

    static async open(storage: EntityStorage) {
        let subspace = await storage.resolveEntityDirectory('simpleEntity');
        let secondaryIndexes: SecondaryIndexDescriptor[] = [];
        let type = t.type({
            id: t.string,
        });
        let validator = function (src: any) {
            type.decode(src);
        };
        let descriptor: EntityDescriptor = {
            name: 'SimpleEntity',
            storageKey: 'simpleEntity',
            subspace, validator, secondaryIndexes, storage
        };
        return new SimpleEntityFactory(descriptor);
    }

    private constructor(descriptor: EntityDescriptor) {
        super(descriptor);
    }

    create(ctx: Context, src: SimpleEntityShape): Promise<SimpleEntity> {
        return this._create(ctx, [src.id], src);
    }

    findById(ctx: Context, id: string): Promise<SimpleEntity | null> {
        return this._findById(ctx, [id]);
    }

    protected _createEntityInstance(value: any): SimpleEntity {
        return new SimpleEntity([value.id], value, this.descriptor);
    }
}

export interface Store extends BaseStore {
    readonly SimpleEntity: SimpleEntityFactory;
}

export async function openStore(storage: EntityStorage): Promise<Store> {
    let SimpleEntityPromise = SimpleEntityFactory.open(storage);
    return {
        storage,
        SimpleEntity: await SimpleEntityPromise,
    };
}
